DROP TABLE IF EXISTS recipes CASCADE;

CREATE TABLE recipes (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) NOT NULL ON DELETE CASCADE,
  recipe_id INTEGER VARCHAR(255) NOT NULL,
  title INTEGER VARCHAR(255),
  image VARCHAR(255)
);